<a href="https://colab.research.google.com/github/Isfhan/mnist-tensorflow-2.0/blob/master/mnist_model.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from __future__ import absolute_import, division, print_function, unicode_literals

try:
  # %tensorflow_version only exists in Colab.
  %tensorflow_version 2.x
except Exception:
  pass

import tensorflow as tf

TensorFlow 2.x selected.


In [0]:
mnist = tf.keras.datasets.mnist

(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0

In [0]:
model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(input_shape=(28, 28)),
  tf.keras.layers.Dense(128, activation='relu'),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(10)
])

In [4]:
predictions = model(x_train[:1]).numpy()
predictions


If you intended to run this layer in float32, you can safely ignore this warning. If in doubt, this warning is likely only an issue if you are porting a TensorFlow 1.X model to TensorFlow 2.

To change all layers to have dtype float64 by default, call `tf.keras.backend.set_floatx('float64')`. To change just this layer, pass dtype='float64' to the layer constructor. If you are the author of this layer, you can disable autocasting by passing autocast=False to the base Layer constructor.



array([[ 0.18378219, -0.35336462, -0.08616923,  0.20342018,  0.01885466,
         0.2847146 ,  0.16119228,  0.1766319 , -0.05110746,  0.0617896 ]],
      dtype=float32)

In [5]:
tf.nn.softmax(predictions).numpy()

array([[0.11150547, 0.06516528, 0.08512513, 0.11371686, 0.09455163,
        0.12334756, 0.1090148 , 0.11071102, 0.0881627 , 0.09869962]],
      dtype=float32)

In [0]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

In [7]:
loss_fn(y_train[:1], predictions).numpy()

2.0927494

In [0]:
model.compile(optimizer='adam',
              loss=loss_fn,
              metrics=['accuracy'])

In [9]:
model.fit(x_train, y_train, epochs=5)

Train on 60000 samples
Epoch 1/5
60000/60000 [==============================] - 4s 71us/sample - loss: 0.3007 - accuracy: 0.9131
Epoch 2/5
60000/60000 [==============================] - 4s 63us/sample - loss: 0.1448 - accuracy: 0.9573
Epoch 3/5
60000/60000 [==============================] - 4s 62us/sample - loss: 0.1080 - accuracy: 0.9678
Epoch 4/5
60000/60000 [==============================] - 4s 63us/sample - loss: 0.0880 - accuracy: 0.9732
Epoch 5/5
60000/60000 [==============================] - 4s 64us/sample - loss: 0.0766 - accuracy: 0.9762


In [10]:
model.evaluate(x_test,  y_test, verbose=2)

10000/10000 - 1s - loss: 0.0677 - accuracy: 0.9795


[0.06766869288659655, 0.9795]

In [0]:
probability_model = tf.keras.Sequential([
  model,
  tf.keras.layers.Softmax()
])

In [12]:
probability_model(x_test[:5])

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[1.1138217e-08, 2.8872256e-09, 7.6659207e-06, 1.2622820e-04,
        2.3335919e-10, 7.0804492e-07, 9.8484411e-15, 9.9985671e-01,
        6.3014140e-06, 2.3793846e-06],
       [2.1422123e-08, 2.9791723e-04, 9.9966669e-01, 6.0316756e-06,
        5.0557432e-13, 3.7405910e-06, 1.3798599e-07, 5.7873633e-11,
        2.5436913e-05, 7.8043240e-12],
       [8.8783473e-08, 9.9903059e-01, 2.5301505e-04, 3.9256297e-06,
        1.6694135e-05, 3.5782796e-06, 8.0026957e-06, 6.0845230e-04,
        7.2676368e-05, 3.0337460e-06],
       [9.9934751e-01, 5.7126675e-07, 7.6972785e-05, 5.8745962e-07,
        2.6709960e-05, 8.3383720e-06, 6.3562082e-05, 4.7486974e-04,
        1.0506247e-07, 7.4171260e-07],
       [8.3966024e-06, 3.4341885e-09, 3.6611405e-06, 1.5858772e-07,
        9.9804270e-01, 2.8723168e-06, 7.4477080e-06, 5.8794118e-05,
        1.8687288e-05, 1.8572612e-03]], dtype=float32)>

In [0]:
model_json  = model.to_json()

In [0]:
with open("model_json", "w") as json_file:
  json_file.write(model_json)

In [0]:
model.save_weights("model.h5")